GET http://localhost:3000

###
POST  http://localhost:3000/auth/login


###
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" : "virus888@gmail.com",
    "password": "12345678"
}


###
POST  http://localhost:3000/auth/refresh-token


###
DELETE  http://localhost:3000/auth/logout